# Generated by Django 3.2.9 on 2021-11-14 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_auto_20211112_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuserprofile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='аватарка'),
        ),
    ]
