# Generated by Django 3.2.9 on 2021-11-14 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_shopuserprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuserprofile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='users_avatars'),
        ),
    ]
